spring.application.name=accounting-docs-spring-security
spring.datasource.url=jdbc:h2:mem:accounting
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=sec
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

